spring:
  application:
    name: prediction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpAddress: true
    hostname: prediction-service
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20

python:
    prediction-service:
        url: http://localhost:5000/
